spring:
  application:
    name: AIspringSSM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.30.128:3306/nlpdatabase
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: huxuzhendashuai@foxmail.com
    password: vyphthacuuwvdeej
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
server:
  port: 8080

